info:
  app:
    name: ${spring.application.name}
    version: 0.0.1
    latest-api-spec: v1
    loaded-profile: ${spring.profiles.active}

spring:
  application:
    name: e-boost-api

management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /system
      exposure:
        include: info,health,loggers
      path-mapping:
        health: /simple

logging.level.reactor.netty.http.client.HttpClient: DEBUG